title: Mike Grawey
description: A portfolio to show the work I've done
theme: just-the-docs

url: https://mgrawey.github.io

aux_links:
  Template Repository: https://github.com/mgrawey/mgrawey.github.io

plugins:
  - jekyll-default-layout

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

# Aux links for the upper right navigation
aux_links:
  "Portfolio Repository":
    - "//github.com/mgrawey/mgrawey.github.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


color_scheme: dark

# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  art300:
    permalink: "/:collection/:path/"
    output: true
  artnm303:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    art300:
      name: ART 300
    artnm303:
      name: ARTNM 303
