title: Mike Grawey's Portfolio
description: A portfolio to show the work I've done
theme: just-the-docs

url: https://mgrawey.github.io

aux_links:
  Template Repository: https://github.com/mgrawey/mgrawey.github.io

plugins:
  - jekyll-default-layout